package com.siebel.asi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-22T14:40:28.418+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://siebel.com/asi/", name = "Default")
@XmlSeeAlso({com.siebel.xml.order_20interface.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Default {

    @WebMethod(operationName = "TMCVCPPUROrderInsertOrUpdate", action = "document/http://siebel.com/asi/:TMCVCPPUROrderInsertOrUpdate")
    @WebResult(name = "TMCVCPPUROrderInsertOrUpdate_Output", targetNamespace = "http://siebel.com/asi/", partName = "TMCVCPPUROrderInsertOrUpdate_Output")
    public TMCVCPPUROrderInsertOrUpdateOutput tmcvcppurOrderInsertOrUpdate(
        @WebParam(partName = "TMCVCPPUROrderInsertOrUpdate_Input", name = "TMCVCPPUROrderInsertOrUpdate_Input", targetNamespace = "http://siebel.com/asi/")
        TMCVCPPUROrderInsertOrUpdateInput tmcvcppurOrderInsertOrUpdateInput
    );

    @WebMethod(operationName = "TMCVCPPUROrderUpdate", action = "document/http://siebel.com/asi/:TMCVCPPUROrderUpdate")
    @WebResult(name = "TMCVCPPUROrderUpdate_Output", targetNamespace = "http://siebel.com/asi/", partName = "TMCVCPPUROrderUpdate_Output")
    public TMCVCPPUROrderUpdateOutput tmcvcppurOrderUpdate(
        @WebParam(partName = "TMCVCPPUROrderUpdate_Input", name = "TMCVCPPUROrderUpdate_Input", targetNamespace = "http://siebel.com/asi/")
        TMCVCPPUROrderUpdateInput tmcvcppurOrderUpdateInput
    );
}
